const fs=require('fs');
eval(fs.readFileSync('build_duas.js','utf8').split('const items=[]')[0]);
const l=fs.readFileSync('taqibat2.txt','utf8').split('\n')[169];
console.log(JSON.stringify(l.slice(0,80)));
const A=pat('اللّٰهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ');
const B=pat('مُحَمَّدٍ');
const mA=new RegExp(A).exec(l); console.log('mA', mA&&JSON.stringify(mA[0]), mA&&mA.index, mA&&mA[0].length);
const mB=new RegExp(B).exec(l); console.log('mB', mB&&mB.index);
console.log('combined', new RegExp(A+'[\\s\\S]*?'+B).test(l));
console.log('after A:', JSON.stringify(l.slice(mA[0].length, mA[0].length+40)));
console.log('B test on after:', new RegExp(B).test(l.slice(mA[0].length)));
