'use strict';
/* نورستان — داور دوئل ۱ به ۱ «آیه‌ساز»؛ ترتیب، امتیاز، زمان و برد فقط روی سرور است. */
const fs = require('fs');
const crypto = require('crypto');
const CFG={rounds:5,roundMs:35000,gapMs:2600,wrongLockMs:1500,maxTiles:6,queueMs:120000,codeMs:300000,maxCodes:200};
const MARK=/^[\u06D6-\u06ED]+$/;
const norm=s=>String(s).replace(/[\u064B-\u065F\u0670\u0640\u06D6-\u06ED]/g,'').replace(/[أإآٱ]/g,'ا').replace(/[^\u0621-\u064A]/g,'');
function buildBank(ayat){const out=[];for(const[key,text]of Object.entries(ayat||{})){const[s,a]=String(key).split(':').map(Number);if(!s||!a||typeof text!=='string')continue;let w=text.trim().split(/\s+/);if(a===1&&s!==1&&norm(w[0])==='بسم')w=w.slice(4);w=w.filter(x=>!MARK.test(x));if(w.length>=3)out.push({key,s,a,words:w});}return out}
function chunk(words,n){if(words.length<=n)return words.slice();const out=[],size=words.length/n;for(let i=0;i<n;i++)out.push(words.slice(Math.round(i*size),Math.round((i+1)*size)).join(' '));return out.filter(Boolean)}
const rid=()=>crypto.randomBytes(5).toString('hex');
function shuffle(arr){const a=arr.slice();for(let i=a.length-1;i>0;i--){const j=crypto.randomInt(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
function createDuel(opts={}){const sendRaw=opts.sendRaw,log=opts.log||(()=>{}),now=opts.now||Date.now(),T=opts.timers||{setTimeout,clearTimeout},cfg={...CFG,...(opts.config||{})};let bank=[];try{const j=opts.ref||JSON.parse(fs.readFileSync(opts.refFile,'utf8'));bank=buildBank(j.ayat)}catch(e){log('⚠️ دوئل: مرجع آیه‌ها خوانده نشد —',e&&e.message)}const queue=[],codes=new Map(),byClient=new Map(),matches=new Set();const send=(c,e)=>{try{sendRaw(c,{to:c.id,...e})}catch(_){}},other=(m,c)=>m.p[0]===c?m.p[1]:m.p[0],alive=c=>!!c&&!(c.sock&&c.sock.destroyed);
function unqueue(c){for(let i=queue.length-1;i>=0;i--)if(queue[i].c===c)queue.splice(i,1);for(const[k,v]of codes)if(v.c===c)codes.delete(k)}function sweep(){const t=now();for(let i=queue.length-1;i>=0;i--){const q=queue[i];if(!alive(q.c)||t-q.at>cfg.queueMs){queue.splice(i,1);if(alive(q.c))send(q.c,{t:'duel:timeout'})}}for(const[k,v]of codes)if(!alive(v.c)||t-v.at>cfg.codeMs)codes.delete(k)}
function start(a,b){if(bank.length<cfg.rounds){for(const x of[a,b])send(x,{t:'duel:error',msg:'بانک آیه‌ها روی سرور آماده نیست'});return}const m={id:rid(),p:[a,b],rounds:shuffle(bank).slice(0,cfg.rounds),ri:-1,st:null,timer:null,over:false,score:{[a.id]:0,[b.id]:0},wins:{[a.id]:0,[b.id]:0}};matches.add(m);byClient.set(a.id,m);byClient.set(b.id,m);for(const x of m.p)send(x,{t:'duel:start',match:m.id,rounds:cfg.rounds,you:{name:x.name},opp:{name:other(m,x).name,level:other(m,x).level||1}});m.timer=T.setTimeout(()=>nextRound(m),cfg.gapMs)}
function nextRound(m){if(m.over)return;m.ri++;if(m.ri>=cfg.rounds)return finish(m,null);const q=m.rounds[m.ri],tiles=chunk(q.words,cfg.maxTiles).map(t=>({id:rid(),t})),order=shuffle(tiles),[a,b]=m.p;m.st={tiles,need:{[a.id]:0,[b.id]:0},lock:{},t0:now(),done:false};for(const x of m.p)send(x,{t:'duel:round',match:m.id,round:m.ri+1,total:cfg.rounds,s:q.s,a:q.a,tiles:order.map(o=>({id:o.id,t:o.t})),ms:cfg.roundMs});m.timer=T.setTimeout(()=>endRound(m,null),cfg.roundMs)}
function pick(c,m,msg){const st=m.st;if(!st||st.done||m.over)return;if(Number(msg.round)!==m.ri+1)return;const t=now(),lockedFor=(st.lock[c.id]||0)-t;if(lockedFor>0)return send(c,{t:'duel:locked',ms:lockedFor});const id=typeof msg.id==='string'?msg.id.slice(0,16):'',k=st.need[c.id],want=st.tiles[k],opp=other(m,c);if(want&&id===want.id){st.need[c.id]=k+1;send(c,{t:'duel:ok',id,n:k+1,of:st.tiles.length});send(opp,{t:'duel:opp',n:k+1,of:st.tiles.length});if(k+1===st.tiles.length)endRound(m,c)}else{st.lock[c.id]=t+cfg.wrongLockMs;send(c,{t:'duel:bad',id,ms:cfg.wrongLockMs});send(opp,{t:'duel:opp-bad'})}}
function endRound(m,winner){const st=m.st;if(!st||st.done||m.over)return;st.done=true;T.clearTimeout(m.timer);const total=st.tiles.length,elapsed=now()-st.t0,gain={};for(const x of m.p){let g=Math.round(st.need[x.id]/total*60);if(winner===x){g=100+Math.round(Math.max(0,1-elapsed/cfg.roundMs)*100);m.wins[x.id]++}gain[x.id]=g;m.score[x.id]+=g}const full=m.rounds[m.ri].words.join(' ');for(const x of m.p)send(x,{t:'duel:roundEnd',round:m.ri+1,won:winner===x,lost:!!winner&&winner!==x,gain:gain[x.id],you:m.score[x.id],opp:m.score[other(m,x).id],full});m.timer=T.setTimeout(()=>nextRound(m),cfg.gapMs)}
function finish(m,quitter){if(m.over)return;m.over=true;T.clearTimeout(m.timer);matches.delete(m);for(const x of m.p)byClient.delete(x.id);const[a,b]=m.p;let win=null;if(quitter)win=other(m,quitter);else if(m.score[a.id]!==m.score[b.id])win=m.score[a.id]>m.score[b.id]?a:b;for(const x of m.p){if(x===quitter)continue;const y=other(m,x);send(x,{t:'duel:end',you:m.score[x.id],opp:m.score[y.id],wins:m.wins[x.id],oppWins:m.wins[y.id],result:!win?'draw':win===x?'win':'lose',forfeit:!!quitter,oppName:y.name})}log(`🏁 دوئل ${m.id} تمام شد`)}
function newCode(){for(let i=0;i<50;i++){const k=String(crypto.randomInt(1000,10000));if(!codes.has(k))return k}return null}
function handle(c,msg){if(!c||!msg)return;sweep();switch(msg.t){case'duel:queue':if(byClient.has(c.id))return send(c,{t:'duel:error',msg:'هم‌اکنون در دوئلی'});unqueue(c);{const q=queue.find(x=>x.c!==c&&alive(x.c));if(q){queue.splice(queue.indexOf(q),1);unqueue(q.c);start(q.c,c)}else{queue.push({c,at:now()});send(c,{t:'duel:waiting'})}}break;case'duel:code':if(byClient.has(c.id))return send(c,{t:'duel:error',msg:'هم‌اکنون در دوئلی'});unqueue(c);if(codes.size>=cfg.maxCodes)return send(c,{t:'duel:error',msg:'سرور شلوغ است — کمی بعد'});{const code=newCode();if(!code)return send(c,{t:'duel:error',msg:'ساخت کد ممکن نشد'});codes.set(code,{c,at:now()});send(c,{t:'duel:waiting',code,ms:cfg.codeMs})}break;case'duel:join':if(byClient.has(c.id))return send(c,{t:'duel:error',msg:'هم‌اکنون در دوئلی'});{const code=String(msg.code==null?'':msg.code).replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/\D/g,'').slice(0,4),e=codes.get(code);if(!e||!alive(e.c))return send(c,{t:'duel:error',msg:'کدی با این شماره پیدا نشد'});if(e.c===c)return send(c,{t:'duel:error',msg:'این کدِ خودت است'});codes.delete(code);unqueue(c);unqueue(e.c);start(e.c,c)}break;case'duel:cancel':unqueue(c);send(c,{t:'duel:cancelled'});break;case'duel:pick':{const m=byClient.get(c.id);if(m)pick(c,m,msg)}break;case'duel:leave':{const m=byClient.get(c.id);if(m)finish(m,c);unqueue(c);send(c,{t:'duel:left'})}break}}
function drop(c){if(!c)return;unqueue(c);const m=byClient.get(c.id);if(m)finish(m,c)}
return{handle,drop,stats:()=>({waiting:queue.length,codes:codes.size,live:matches.size,bank:bank.length}),_state:{queue,codes,byClient,matches,bank,cfg}}}
module.exports={createDuel,buildBank,chunk,CFG};
